#!/usr/bin/env php
<?php

/**
 * Demo script to showcase Blade template functionality
 * Run with: php demo-blade-templates.php
 */

require_once 'vendor/autoload.php';

use App\Models\Page;
use App\Models\Site;
use App\Models\Template;
use App\Models\TemplateContent;
use App\Services\BladeTemplateService;
use Illuminate\Foundation\Application;

// Bootstrap Laravel
$app = new Application(realpath(__DIR__));
$app->singleton(
    Illuminate\Contracts\Http\Kernel::class,
    App\Http\Kernel::class
);
$app->singleton(
    Illuminate\Contracts\Console\Kernel::class,
    App\Console\Kernel::class
);
$app->singleton(
    Illuminate\Contracts\Debug\ExceptionHandler::class,
    App\Exceptions\Handler::class
);

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

echo "🚀 Sitewise Blade Template Demo\n";
echo "================================\n\n";

try {
    // Find or create a demo site
    $site = Site::firstOrCreate(
        ['domain' => 'demo.local'],
        [
            'name' => 'Blade Template Demo',
            'settings' => ['description' => 'Demo site for Blade templates'],
            'active' => true,
        ]
    );

    // Bind site to app for global scope
    app()->instance('site', $site);

    echo "✅ Site: {$site->name} ({$site->domain})\n";

    // Create a demo template with Blade template
    $template = Template::firstOrCreate(
        [
            'site_id' => $site->id,
            'name' => 'Demo Landing Page',
        ],
        [
            'description' => 'A demo template showcasing Blade rendering',
            'structure' => [
                [
                    'name' => 'Page Title',
                    'key' => 'page_title',
                    'type' => 'text',
                    'required' => true,
                    'description' => 'The main page title',
                ],
                [
                    'name' => 'Hero Message',
                    'key' => 'hero_message',
                    'type' => 'textarea',
                    'required' => true,
                    'description' => 'Hero section message',
                ],
                [
                    'name' => 'Features',
                    'key' => 'features',
                    'type' => 'rich_text',
                    'required' => false,
                    'description' => 'Feature list',
                ],
            ],
            'blade_template' => '<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $page_title }} - {{ $site_name }}</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 0; padding: 20px; background: #f5f5f5; }
        .container { max-width: 800px; margin: 0 auto; background: white; padding: 40px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        .hero { text-align: center; padding: 40px 0; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; border-radius: 10px; margin-bottom: 30px; }
        .hero h1 { font-size: 2.5rem; margin-bottom: 1rem; }
        .hero p { font-size: 1.2rem; opacity: 0.9; }
        .features { margin-top: 30px; }
        .footer { text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #eee; color: #666; }
    </style>
</head>
<body>
    <div class="container">
        <div class="hero">
            <h1>{{ $page_title }}</h1>
            <p>{{ $hero_message }}</p>
        </div>
        
        @if($features)
        <div class="features">
            <h2>Features</h2>
            {!! $features !!}
        </div>
        @endif
        
        <div class="footer">
            <p>Generated by Sitewise Blade Templates</p>
            <p><small>Site: {{ $site_name }} | Domain: {{ $site_domain }}</small></p>
        </div>
    </div>
</body>
</html>',
            'active' => true,
        ]
    );

    echo "✅ Template: {$template->name}\n";

    // Create a demo page
    $page = Page::firstOrCreate(
        [
            'site_id' => $site->id,
            'slug' => 'blade-demo',
        ],
        [
            'title' => 'Blade Template Demo Page',
            'response_type' => 'template',
            'template_id' => $template->id,
            'active' => true,
        ]
    );

    echo "✅ Page: {$page->title} (/{$page->slug})\n";

    // Add template content
    $contentData = [
        'page_title' => 'Welcome to Blade Templates!',
        'hero_message' => 'Experience the power of dynamic content rendering with Laravel Blade templates in Sitewise.',
        'features' => '<ul>
            <li><strong>Dynamic Content:</strong> Template fields become Blade variables</li>
            <li><strong>Full Control:</strong> Complete HTML structure customization</li>
            <li><strong>Laravel Integration:</strong> Use all Blade features and directives</li>
            <li><strong>Responsive Design:</strong> Mobile-first approach</li>
        </ul>',
    ];

    foreach ($contentData as $key => $value) {
        TemplateContent::updateOrCreate(
            [
                'page_id' => $page->id,
                'template_id' => $template->id,
                'key' => $key,
            ],
            ['value' => $value]
        );
    }

    echo "✅ Template content added\n\n";

    // Render the page using Blade template
    echo "🎨 Rendering Blade Template...\n";
    echo "==============================\n\n";

    $renderedHtml = BladeTemplateService::renderPage($page);

    // Save rendered HTML to a file for viewing
    $outputFile = 'blade-demo-output.html';
    file_put_contents($outputFile, $renderedHtml);

    echo "✅ Page rendered successfully!\n";
    echo "📄 Output saved to: {$outputFile}\n";
    echo "🌐 Open the file in your browser to see the result\n\n";

    // Show available variables
    echo "📋 Available Template Variables:\n";
    echo "================================\n";
    $variables = BladeTemplateService::getAvailableVariables($template);
    foreach ($variables as $var => $description) {
        echo "• \${$var} - {$description}\n";
    }

    echo "\n🎉 Demo completed successfully!\n";
    echo "\nTo see the Blade template in action:\n";
    echo "1. Open {$outputFile} in your browser\n";
    echo "2. Or visit http://localhost/blade-demo (if server is running)\n";
    echo "3. Check the admin panel to edit template content\n";

} catch (Exception $e) {
    echo '❌ Error: '.$e->getMessage()."\n";
    echo "Stack trace:\n".$e->getTraceAsString()."\n";
}
