<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $page_title }} - {{ $site_name }}</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 0; padding: 20px; }
        .container { max-width: 800px; margin: 0 auto; }
        .header { border-bottom: 1px solid #ccc; padding-bottom: 20px; margin-bottom: 20px; }
        .content { line-height: 1.6; }
    </style>
</head>
<body>
    <div class="container">
        <header class="header">
            <h1>{{ $page_title }}</h1>
            <p>Site: {{ $site_name }} ({{ $site_domain }})</p>
        </header>
        
        <main class="content">
            {{-- Ffe23cef-aa52-4a83-8787-eb4d70e4e1b7 --}}
            <div class="ffe23cef-aa52-4a83-8787-eb4d70e4e1b7">{{ $ffe23cef-aa52-4a83-8787-eb4d70e4e1b7 }}</div>
            
        </main>
        
        <footer>
            <p><small>Generated by Sitewise Template System</small></p>
        </footer>
    </div>
</body>
</html>